# Generated by Django 2.2.2 on 2019-06-23 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190623_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 23, 14, 22, 58, 683609, tzinfo=utc)),
        ),
    ]
