# Generated by Django 2.2.5 on 2019-09-10 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190623_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 10, 12, 8, 33, 125048, tzinfo=utc)),
        ),
    ]
