# Generated by Django 2.2.5 on 2019-09-11 03:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190911_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 11, 3, 12, 30, 818703, tzinfo=utc)),
        ),
    ]
