# Generated by Django 2.2.3 on 2019-09-11 05:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190911_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 11, 5, 39, 1, 558777, tzinfo=utc)),
        ),
    ]
